# See https://reuse.software/spec-3.3/#reusetoml for specification
version = 1


[[annotations]]
path = [
    "Makefile",
    "*.mk",
    "**/Build.act",
    "gen/**",
    "src/**",
    "test/**",
    "**/snapshots/expected/**",

]
SPDX-FileCopyrightText = "Deutsche Telekom AG"
SPDX-License-Identifier = "BSD-3-Clause"


[[annotations]]
path = [
    ".gitignore",
    ".gitmodules",
    "README.md",
    "REUSE.toml",
    ".github/**"
]
SPDX-FileCopyrightText = "Deutsche Telekom AG"
SPDX-License-Identifier = "CC0-1.0"
